name: Website CI

on:
  workflow_dispatch:
  push:
    paths:
      - "website/*"
      - ".github/workflows/website.yml"
      - ".github/config/lighthouserc.json"
      - ".github/config/budget.json"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Load repo
      uses: actions/checkout@v2
    
    - name: Audit using Lighthouse CI
      uses: treosh/lighthouse-ci-action@v2
      with:
        # no urls needed, since it uses local folder to scan .html files
        configPath: "./.github/config/lighthouserc.json"
        budgetPath: ".github/config/budget.json"
        uploadArtifacts: true
        temporaryPublicStorage: true
